
export const GLOBALS = {};

GLOBALS.WALLET_TYPE_COINBASE = 'Coinbase WalletLink';
GLOBALS.WALLET_TYPE_FORTMATIC = 'Fortmatic';
GLOBALS.WALLET_TYPE_TORUS = 'Torus';
GLOBALS.WALLET_TYPE_METAMASK = 'MetaMask';
GLOBALS.WALLET_TYPE_NATIVE = 'Native';
